<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_menu().
 *
 * Adds a page that displays some text.
 */
function madlibs_menu() {
   $items['madlib'] = array(
      'title' => "Madlib viewer",
      'page callback' => 'madlib_viewer',
      'access callback' => TRUE,
    );
    return $items;
}

/**
 * Page callback to show a madlib form and results.
 */
function madlib_viewer() {

  drupal_add_js(drupal_get_path('module', 'madlibs') .'/js/madlibs_maker.js', 'file');

  $text = <<< EOD
   <div id="madlibs">

    <p>
      Come for the software, stay for the community <br />
      Drupal is an open source content management <span rel="madlib" type="noun" desc="Thing you stand on">platform</span>
      powering millions of <span rel="madlib" type="noun" desc="Things found on the internet">websites</span>
      and <span rel="madlib" type="noun" desc="Plural noun">applications</span>.
      It’s built, <span rel="madlib" type="verb" desc="A verb, past-tense">used</span>,
      and supported by a(n) <span rel="madlib" type="adjective" desc="Adjective">active</span>
      and <span rel="madlib" type="adjective" desc="Adjective">diverse</span> community of
      <span rel="madlib" type="noun" desc="A kind of animal, plural">people</span> around the world.
    </p>
  </div>
EOD;

  return $text;
}
